version: "3"
services:
    db:
        image: postgres:latest
        restart: unless-stopped
        container_name: sudoku-backend-db
        volumes: 
            - db_postgres:/var/lib/postgresql/data
        env_file: 
            - .env
    backend:
        build: ./code
        container_name: sudoku-backend-backend
        restart: unless-stopped
        ports: 
            - "${DJANGO_PORT}:8000"
        env_file: 
            - .env
        volumes:
            - ./code:/code
        depends_on: 
            - db

volumes:
    db_postgres: