name: CI

on:
  pull_request:
    paths-ignore:
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - '.env.template'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Test with tox
        run: |
          chmod +x ./scripts/run_ci.sh
          ./scripts/run_ci.sh
